###############################################################################
# add library
#
OBJ += main.o

VPATH += example01$(DIR)src

INCLUDE += -Iexample01$(DIR)inc

CFGFILES += example01$(DIR)etc$(DIR)example01.oil

CLEAN += example01clean

example01clean :


