###############################################################################
# add library
#
OBJ +=	main.o

VPATH += examples$(DIR)Com$(DIR)src \
			examples$(DIR)Com$(DIR)asm

INCLUDE += -Iexamples$(DIR)Com$(DIR)inc

CFGFILES += examples$(DIR)Com$(DIR)etc$(DIR)FreeOSEK.oil					\
				examples$(DIR)Com$(DIR)etc$(DIR)OpenCOM.oil					\
				examples$(DIR)Com$(DIR)etc$(DIR)$(BOARD)$(DIR)OpenDRV.oil
				

CLEAN += comclean

comclean :

