###############################################################################
# add library
#
OBJ +=	main.o

VPATH += examples$(DIR)armexample$(DIR)src \
			examples$(DIR)armexample$(DIR)asm

INCLUDE += -Iexamples$(DIR)armexample$(DIR)inc

CFGFILES += examples$(DIR)armexample$(DIR)etc$(DIR)OpenDRV.oil			\
				examples$(DIR)armexample$(DIR)etc$(DIR)OpenSEK.oil

CLEAN += armexampleclean

armexampleclean :

