###############################################################################
# add library
#
OBJ += 	ctest_rst.o			\
			ctest_tm_01.o

VPATH += FreeOSEK$(DIR)tst$(DIR)ctest$(DIR)src

INCLUDE += -IFreeOSEK$(DIR)tst$(DIR)ctest$(DIR)inc

CFGFILES += FreeOSEK$(DIR)tst$(DIR)ctest$(DIR)etc$(DIR)ctest_tm_01_01.oil			\
				FreeOSEK$(DIR)tst$(DIR)ctest$(DIR)etc$(DIR)OpenDRV.oil

GENFILES += FreeOSEK$(DIR)tst$(DIR)ctest$(DIR)gen$(DIR)inc$(DIR)ctest_cfg.h.php

CLEAN += ctestclean

CFLAGS += -DCT_TM_01

ctestclean :


