###############################################################################
# add library
#
OBJ += main.o

VPATH += examples$(DIR)example01$(DIR)src

INCLUDE += -Iexamples$(DIR)example01$(DIR)inc

CFGFILES += examples$(DIR)example01$(DIR)etc$(DIR)example01.oil

CLEAN += example01clean

example01clean :


