##############################################################################
# add library
#
OPENOSEK_OBJ +=	Osek_Internal_Arch_Cpu.o

VPATH		+=		OpenSEK$(DIR)src$(DIR)$(ARCH)$(DIR)$(CPUTYPE)
INCLUDE += 		-IOpenSEK$(DIR)inc$(DIR)$(ARCH)$(DIR)$(CPUTYPE)
