DRV_ETH_OBJ +=	EthPhy_Init.o										\
					EthPhy_Init_Arch.o

INCLUDE += 	-IFreeOSEK$(DIR)Drv$(DIR)Eth$(DIR)Phy$(DIR)inc					\
				-IFreeOSEK$(DIR)Drv$(DIR)Eth$(DIR)Phy$(DIR)inc$(DIR)$(PHY)

VPATH += FreeOSEK$(DIR)Drv$(DIR)Eth$(DIR)Phy$(DIR)src							\
			FreeOSEK$(DIR)Drv$(DIR)Eth$(DIR)Phy$(DIR)src$(DIR)$(PHY)

GENFILES +=
