###############################################################################
# add library
#
OBJ += 	crt.o 	\
			main.o	\

VPATH += armexample$(DIR)src \
			armexample$(DIR)asm

INCLUDE += -Iarmexample$(DIR)inc

CFGFILES +=

CLEAN += armexampleclean

armexampleclean :


