###############################################################################
# add library
#
OBJ += 	main.o	\
			crt.o

VPATH += armexample$(DIR)src \
			armexample$(DIR)asm

INCLUDE += -Iarmexample$(DIR)inc

CFGFILES +=

CLEAN += armexampleclean

armexampleclean :


