###############################################################################
# add library
#
OBJ +=	main.o

VPATH += armexample$(DIR)src \
			armexample$(DIR)asm

INCLUDE += -Iarmexample$(DIR)inc

CFGFILES += armexample$(DIR)etc$(DIR)OpenDRV.oil

CLEAN += armexampleclean

armexampleclean :


