###############################################################################
# add library
#
OBJ += main.o

VPATH += moduletest01$(DIR)src

INCLUDE += -Imoduletest01$(DIR)inc

CFGFILES += moduletest01$(DIR)etc$(DIR)moduletest01.oil			\
				moduletest01$(DIR)etc$(DIR)testsuite.oil				\
				moduletest01$(DIR)etc$(DIR)seENC.oil

CLEAN += moduletest01clean

moduletest01clean :


