###############################################################################
# add library
#
OBJ +=	main.o

VPATH += examples$(DIR)BlinkingNetduino$(DIR)src \
			examples$(DIR)BlinkingNetduino$(DIR)asm

INCLUDE += -Iexamples$(DIR)BlinkingNetduino$(DIR)inc

CFGFILES += examples$(DIR)BlinkingNetduino$(DIR)etc$(DIR)FreeOSEK.oil				\
				examples$(DIR)BlinkingNetduino$(DIR)etc$(DIR)$(BOARD)$(DIR)Drv.oil

CLEAN += blinkingnetduinoclean

blinkingnetduinoclean :

