##############################################################################
# add library
#
-include $(GENDIR)$(DIR)mak$(DIR)Make_OpenDRV.mak

LIB +=

GEN +=

LFLAGS +=

OPENOSEK_OBJ +=

GENFILES += OpenDRV$(DIR)gen$(DIR)mak$(DIR)Make_OpenDRV.mak.php

VPATH +=

INCLUDE +=

#OpenSEK.a : $(OPENOSEK_OBJ)
#	ar -rcs $(LIBDIR)$(DIR)OpenSEK.a $(foreach obj, $(OPENOSEK_OBJ), $(OBJDIR)$(DIR)$(obj))

#SPLINT +=	OpenSEK$(DIR)src$(DIR)*.c \
#				OpenSEK$(DIR)src$(DIR)$(ARCH)*.c \
#				OpenSEK$(DIR)src$(DIR)$(ARCH)$(DIR)$(DERIVATE)$(DIR)*.c
