############################################################################### 
#
# Copyright 2008, Mariano Cerdeiro
#
# This file is part of FreeOSEK.
#
# FreeOSEK is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FreeOSEK is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FreeOSEK. If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

###############################################################################
# includes
-include OpenGEN$(DIR)mak$(DIR)$(ARCH)$(DIR)$(COMPILER)$(DIR)Makefile

###############################################################################
# definitions
#OpenGEN_OBJ += start.o

LINKSCRIPT = -TOpenGEN$(DIR)ld$(DIR)$(ARCH)$(DIR)lpc2468$(DIR)lpc_e2468.cmd
#-TOpenGEN$(DIR)ld$(DIR)lpc2468$(DIR)lpc2468.cmd
