##############################################################################
# add library
#
OPENOSEK_OBJ +=	Osek_Internal_Arch_Cpu.o

VPATH		+=		FreeOSEK$(DIR)src$(DIR)$(ARCH)$(DIR)$(CPUTYPE)
INCLUDE += 		-IFreeOSEK$(DIR)inc$(DIR)$(ARCH)$(DIR)$(CPUTYPE)
