###############################################################################
# add library
#
OBJ +=	main.o

VPATH += examples$(DIR)Blinking$(DIR)src \
			examples$(DIR)Blinking$(DIR)asm

INCLUDE += -Iexamples$(DIR)Blinking$(DIR)inc

CFGFILES += examples$(DIR)Blinking$(DIR)etc$(DIR)FreeOSEK.oil					\
				examples$(DIR)Blinking$(DIR)etc$(DIR)$(BOARD)$(DIR)Drv.oil

CLEAN += blinkingclean

blinkingclean :

