OPENDRV_ETH_OBJ +=		EthPhy_Init.o

INCLUDE += 	-IOpenDRV$(DIR)Eth$(DIR)Phy$(DIR)inc					\
				-IOpenDRV$(DIR)Eth$(DIR)Phy$(DIR)inc$(DIR)$(PHY)

VPATH += OpenDRV$(DIR)Eth$(DIR)Phy$(DIR)src

GENFILES +=
