###############################################################################
# add library
#
OBJ +=	main.o

VPATH += examples$(DIR)uIP$(DIR)src \
			examples$(DIR)uIP$(DIR)asm

INCLUDE += -Iexamples$(DIR)uIP$(DIR)inc

CFGFILES += examples$(DIR)uIP$(DIR)etc$(DIR)OpenSEK.oil					\
				examples$(DIR)uIP$(DIR)etc$(DIR)$(BOARD)$(DIR)OpenDRV.oil

CLEAN += blinkingclean

blinkingclean :

