###############################################################################
# add library
#
OBJ += main.o

VPATH += tst$(DIR)moduletest01$(DIR)src

INCLUDE += -Itst$(DIR)moduletest01$(DIR)inc

CFGFILES += tst$(DIR)moduletest01$(DIR)etc$(DIR)moduletest01.oil			\
				tst$(DIR)moduletest01$(DIR)etc$(DIR)testsuite.oil				\
				tst$(DIR)moduletest01$(DIR)etc$(DIR)OpenDRV.oil					\
				tst$(DIR)moduletest01$(DIR)etc$(DIR)OpenGEN.oil					\
				tst$(DIR)moduletest01$(DIR)etc$(DIR)seENC.oil

CLEAN += moduletest01clean

moduletest01clean :


